### ISSUE TITLE
Error with includes

### ISSUE THREAD

**Issue by rjurado01** [rjurado01/as_json_representations#7]
```
1) Api::V01::ClientsController GET #index when platform is logged when platform has permissions filters when kind is used when partial matching are used returns 200 http status code
     Failure/Error:
       render json: {data: clients&.as_json(representation: representation),
                     meta: pagination_meta(clients)}, status: 200
     
     NoMethodError:
       undefined method `representations' for NilClass:Class
     # /home/dluque/.asdf/installs/ruby/2.6.0/lib/ruby/gems/2.6.0/bundler/gems/as_json_representations-2ae4b771fe07/lib/as_json_representations/collection.rb:14:in `block in as_json'
     # /home/dluque/.asdf/installs/ruby/2.6.0/lib/ruby/gems/2.6.0/bundler/gems/as_json_representations-2ae4b771fe07/lib/as_json_representations/collection.rb:11:in `each'
     # /home/dluque/.asdf/installs/ruby/2.6.0/lib/ruby/gems/2.6.0/bundler/gems/as_json_representations-2ae4b771fe07/lib/as_json_representations/collection.rb:11:in `as_json'
     # ./app/controllers/api/v01/clients_controller.rb:12:in `index'
```
